-- 코드를 입력하세요
## SELECT 서브쿼리 방법
SELECT CATEGORY, MAX(PRICE) as MAX_PRICE, (SELECT PRODUCT_NAME FROM FOOD_PRODUCT WHERE CATEGORY = f.CATEGORY ORDER BY PRICE DESC LIMIT 1) as PRODUCT_NAME
FROM FOOD_PRODUCT f
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY
ORDER BY PRICE DESC;

## WHERE 다중행 서브쿼리 방법
# SELECT CATEGORY, PRICE as MAX_PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE (CATEGORY, PRICE) IN (
#     SELECT CATEGORY, MAX(PRICE)
#     FROM FOOD_PRODUCT
#     GROUP BY CATEGORY
#     HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
# )
# ORDER BY PRICE DESC;