-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO r
WHERE FAVORITES = (SELECT FAVORITES FROM REST_INFO WHERE FOOD_TYPE = r.FOOD_TYPE ORDER BY FAVORITES DESC LIMIT 1)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC;